import type { Buyer } from '@wholesale-ai/shared';
import { BuyerStrategy, PropertyType } from '@wholesale-ai/shared';
import { NextResponse } from 'next/server';

const mockBuyers: Buyer[] = [
  {
    id: 'buyer-001',
    name: 'Mike Reynolds',
    email: 'mike@reynoldsrei.com',
    phone: '214-555-1001',
    company: 'Reynolds REI',
    buyBox: {
      geographies: [
        {
          city: 'Dallas',
          state: 'TX',
          county: 'Dallas',
          zipCodes: ['75201', '75202', '75203'],
        },
        { city: 'Fort Worth', state: 'TX', county: 'Tarrant' },
      ],
      strategies: [BuyerStrategy.FIX_AND_FLIP, BuyerStrategy.WHOLETAIL],
      propertyTypes: [PropertyType.SINGLE_FAMILY],
      priceMin: 50000,
      priceMax: 200000,
      bedsMin: 2,
      bedsMax: 4,
      sqftMin: 1000,
      sqftMax: 2500,
      acceptableConditions: ['fair', 'poor'],
    },
    verified: true,
    vip: true,
    stats: {
      dealsReceived: 45,
      dealsViewed: 42,
      dealsClosed: 12,
      totalVolume: 1850000,
      avgResponseTime: 2.5,
      lastActive: new Date(Date.now() - 3600000).toISOString(),
    },
    notes: 'Prefers deals under $150k. Fast closer.',
    createdAt: new Date(Date.now() - 31536000000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'buyer-002',
    name: 'Jennifer Chen',
    email: 'jen@dfwhomes.com',
    phone: '469-555-2002',
    company: 'DFW Homes LLC',
    buyBox: {
      geographies: [
        { city: 'Plano', state: 'TX', county: 'Collin' },
        { city: 'Dallas', state: 'TX', county: 'Dallas' },
      ],
      strategies: [BuyerStrategy.BUY_AND_HOLD, BuyerStrategy.FIX_AND_FLIP],
      propertyTypes: [PropertyType.SINGLE_FAMILY, PropertyType.MULTI_FAMILY],
      priceMin: 100000,
      priceMax: 350000,
      bedsMin: 3,
      bedsMax: 5,
      sqftMin: 1500,
      sqftMax: 4000,
      acceptableConditions: ['good', 'fair'],
    },
    verified: true,
    vip: false,
    stats: {
      dealsReceived: 28,
      dealsViewed: 25,
      dealsClosed: 7,
      totalVolume: 1200000,
      avgResponseTime: 4.2,
      lastActive: new Date(Date.now() - 172800000).toISOString(),
    },
    notes: 'Building rental portfolio',
    createdAt: new Date(Date.now() - 15768000000).toISOString(),
    updatedAt: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: 'buyer-003',
    name: 'Carlos Martinez',
    email: 'carlos@martinezinvest.com',
    phone: '817-555-3003',
    company: 'Martinez Investments',
    buyBox: {
      geographies: [
        { city: 'Fort Worth', state: 'TX', county: 'Tarrant' },
        { city: 'Arlington', state: 'TX', county: 'Tarrant' },
      ],
      strategies: [
        BuyerStrategy.SUBJECT_TO,
        BuyerStrategy.CREATIVE_FINANCE,
        BuyerStrategy.BUY_AND_HOLD,
      ],
      propertyTypes: [PropertyType.SINGLE_FAMILY],
      priceMin: 80000,
      priceMax: 250000,
      bedsMin: 2,
      bedsMax: 4,
      sqftMin: 1000,
      sqftMax: 2500,
      acceptableConditions: ['good', 'fair', 'poor'],
    },
    verified: true,
    vip: false,
    stats: {
      dealsReceived: 35,
      dealsViewed: 30,
      dealsClosed: 9,
      totalVolume: 980000,
      avgResponseTime: 3.0,
      lastActive: new Date(Date.now() - 7200000).toISOString(),
    },
    notes: 'Creative finance specialist',
    createdAt: new Date(Date.now() - 20000000000).toISOString(),
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'buyer-004',
    name: 'Amanda Foster',
    email: 'amanda.foster@email.com',
    phone: '972-555-4004',
    company: null,
    buyBox: {
      geographies: [
        { city: 'Irving', state: 'TX', county: 'Dallas' },
        { city: 'Garland', state: 'TX', county: 'Dallas' },
      ],
      strategies: [BuyerStrategy.FIX_AND_FLIP],
      propertyTypes: [PropertyType.SINGLE_FAMILY],
      priceMin: 40000,
      priceMax: 120000,
      bedsMin: 2,
      bedsMax: 3,
      sqftMin: 800,
      sqftMax: 1800,
      acceptableConditions: ['fair', 'poor'],
    },
    verified: false,
    vip: false,
    stats: {
      dealsReceived: 12,
      dealsViewed: 10,
      dealsClosed: 2,
      totalVolume: 180000,
      avgResponseTime: 8.5,
      lastActive: new Date(Date.now() - 864000000).toISOString(),
    },
    notes: 'New investor, smaller deals',
    createdAt: new Date(Date.now() - 7776000000).toISOString(),
    updatedAt: new Date(Date.now() - 864000000).toISOString(),
  },
  {
    id: 'buyer-005',
    name: 'David Park',
    email: 'david@parkproperties.com',
    phone: '682-555-5005',
    company: 'Park Properties Group',
    buyBox: {
      geographies: [
        {
          city: 'Dallas',
          state: 'TX',
          county: 'Dallas',
          zipCodes: ['75201', '75204', '75205', '75206'],
        },
      ],
      strategies: [BuyerStrategy.WHOLETAIL, BuyerStrategy.FIX_AND_FLIP],
      propertyTypes: [PropertyType.SINGLE_FAMILY, PropertyType.CONDO],
      priceMin: 150000,
      priceMax: 400000,
      bedsMin: 2,
      bedsMax: 5,
      sqftMin: 1200,
      sqftMax: 3500,
      acceptableConditions: ['excellent', 'good', 'fair'],
    },
    verified: true,
    vip: true,
    stats: {
      dealsReceived: 60,
      dealsViewed: 58,
      dealsClosed: 18,
      totalVolume: 3200000,
      avgResponseTime: 1.5,
      lastActive: new Date(Date.now() - 1800000).toISOString(),
    },
    notes: 'Premium buyer, quick decisions',
    createdAt: new Date(Date.now() - 63072000000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
];

export { mockBuyers };

export async function GET() {
  return NextResponse.json({ buyers: mockBuyers });
}
